services:
  - type: web
    name: foodstore-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://ecommerce-nw38.onrender.com
